default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_commander_development
  username: rails_commander
  password: '337'
  host: localhost

test:
  <<: *default
  database: rails_commander_test
  username: rails_commander
  password: '337'
  host: localhost

production:
  <<: *default
  database: rails_commander_production
